import { ClientProvider } from "./ClientProvider";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
      <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
